services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_1_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_1_PASS}
    ports:
      - "${MONGO_1_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  server:
    build:
      context: ..
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      SALT: ${SALT}
      MONGO_1_DB_NAME: ${MONGO_1_DB_NAME}
      MONGO_1_HOST: ${MONGO_1_HOST}
      MONGO_1_PORT: ${MONGO_1_PORT}
      MONGO_1_USER: ${MONGO_1_USER}
      MONGO_1_PASS: ${MONGO_1_PASS}
      RABBITMQ_1_USER: ${RABBITMQ_1_USER}
      RABBITMQ_1_PASSWORD: ${RABBITMQ_1_USER}
      RABBITMQ_1_PORT: ${RABBITMQ_1_PORT}
      RABBITMQ_1_HOST: ${RABBITMQ_1_HOST}
      KAFKA_1_HOST: ${KAFKA_1_HOST}
      KAFKA_1_PORT: ${KAFKA_1_PORT}
      NAKAMA_HOST: ${NAKAMA_HOST}
      NAKAMA_PORT: ${NAKAMA_PORT}
      NAKAMA_SERVER_KEY: ${NAKAMA_SERVER_KEY}
      NAKAMA_USE_SSL: ${NAKAMA_USE_SSL}
      NAKAMA_AUTHENTICATION_ID: ${NAKAMA_AUTHENTICATION_ID}
      TELEGRAM_CIWALLET_BOT_TOKEN: ${TELEGRAM_CIWALLET_BOT_TOKEN}
      TELEGRAM_CIFARM_BOT_TOKEN: ${TELEGRAM_CIFARM_BOT_TOKEN}
      TELEGRAM_MOCK_AUTHORIZATION: ${TELEGRAM_MOCK_AUTHORIZATION}
      
      POSTGRES_1_DB_NAME: ${POSTGRES_1_DB_NAME}
      POSTGRES_1_HOST: ${POSTGRES_1_HOST}
      POSTGRES_1_PORT: ${POSTGRES_1_PORT}
      POSTGRES_1_USER: ${POSTGRES_1_USER}
      POSTGRES_1_PASS: ${POSTGRES_1_PASS}
    ports:
      - 9999:9999
volumes:
  mongo_data: