type NftData {
  tokenId: Int!
  tokenURI: String
}

type GetNftsByOwnerAddressResponse {
  records: [NftData!]!
  count: Int!
}

type GetNftsByTokenIdsResponse {
  records: [NftData!]!
}

type Query {
  nftsByOwnerAddress(args: GetNftsByOwnerAddressArgs!): GetNftsByOwnerAddressResponse!
  nftsByTokenIds(args: GetNftsByTokenIdsArgs!): GetNftsByTokenIdsResponse!
}

input GetNftsByOwnerAddressArgs {
  input: GetNftsByOwnerAddressFilter
  filter: GetNftsByOwnerAddressFilter
}

input GetNftsByOwnerAddressFilter {
  skip: Int
  take: Int
}

input GetNftsByTokenIdsArgs {
  input: GetNftByTokenIdsInput
}

input GetNftByTokenIdsInput {
  tokenIds: [ID!]!
  network: String
  nftKey: String
  chainKey: String
}